const contractTr = `Vertex Kadro Sözleşmesi

Giriş ve Kapsam
Bu belge, İngiltere ve Galler şirketler siciline 17133522 numarası ile tescilli olan ve bundan böyle Vertex olarak anılacak olan Vertex Corporation LTD bünyesinde yapılan işlere destek veren kişilerin, bundan böyle Katkıcı olarak anılacaktır, uyması gereken temel prensipleri düzenler. İşbu sözleşme ile Katkıcı'nın dahil olabileceği özel ekiplere ait spesifik sözleşmeler arasında herhangi bir hüküm uyuşmazlığı olması halinde, ilgili özel sözleşmenin hükümleri öncelikli olarak geçerli sayılacaktır.

1. Statü
Katkıcı, Vertex ekosisteminde bulunduğu süre zarfında Vertex’in resmi bir çalışanı, işçisi veya acentesi olmadığını kabul eder. Taraflar arasında herhangi bir işçi-işveren ilişkisi bulunmamaktadır. Bu katılım; ortak vizyon doğrultusunda deneyim kazanma, ekosisteme destek olma ve teknolojik projelere değer katma amacı taşır. Katkıcı’ya bu faaliyetleri karşılığında sabit bir maaş, ücret veya sigorta taahhüdünde bulunulmamıştır. Bununla birlikte Katkıcı, yalnızca işbu sözleşme yürürlükte kaldığı ve Vertex ekosisteminin aktif bir parçası olmaya devam ettiği süre boyunca, edindiği bu deneyimi ve üstlendiği rolü profesyonel özgeçmişinde belirtebilir ve referans olarak gösterebilir. Ayrıca Katkıcı, gösterdiği üstün performans ve aidiyet doğrultusunda ilerleyen süreçte ekosistemin üst kademelerine yükselme, stratejik pozisyonlarda görev alma ve Vertex'in ortaklarından biri olma gibi fırsatları elde etme imkanına sahiptir.

2. Temsilci İzni
Katkıcı’nın yasal sorumlulukları bulunduğu ülkenin kanunlarına tabidir. Katkıcı, eğer 18 yaşından küçük ise dijital sistem üzerinden bu metni onaylayarak ve Vertex ekosistemine dahil olarak; yapılan işlere katılmak, içerik üretmek, Vertex’i temsil etmek ve bu belgede söz konusu olan Vertex adına yaptığı işlerden doğan fikri mülkiyet haklarının devrini gerçekleştirmek için yasal velisinden veya vasisinden tam yetki ve izin aldığını beyan ve taahhüt eder.

3. Fikri Mülkiyet
Katkıcı’nın, Vertex ekosistemindeki projelere sağladığı emek ve katkı tartışmasız bir şekilde kabul edilir ve onurlandırılır. Katkıcı, bu belgede yer alan “kötü ayrılık” statüsünde Vertex ile olan ilişkisini sonlandırmadığı sürece, yer aldığı projelerin ismini referans göstererek bu çalışmalara katkı sağladığını özgürce ifade etme ve bunu portföyünde sergileme hakkına daima sahiptir. Bununla birlikte, projelerin küresel vizyonunu, sürdürülebilirliğini ve bütünlüğünü korumak amacıyla; ekosistem dahilinde üretilen veya sisteme dahil edilen her türlü yazılım, kod, tasarım, algoritma, strateji ve fikrin tüm isim, yürütme, işletme, geliştirme ve ticari hakları münhasıran Vertex'e aittir. Katkıcı, sağladığı katkıların ticari ve operasyonel tasarruf yetkisinin tamamen Vertex'te olduğunu kabul ve beyan eder.

4. Gizlilik
Katkıcı, Vertex topluluğu içinde bulunduğu süre boyunca eriştiği hiçbir stratejik planı, duyurulmamış projeyi, kod, tasarım ve mimari gibi teknik verileri veya önemli ve kritik nitelikteki iç yazışmaları Vertex’in yazılı onayı olmadan üçüncü şahıslarla, sosyal medyada veya halka açık platformlarda paylaşamaz. Katkıcı, Vertex bünyesinde öğrendiği gizli ve kritik öneme sahip hiçbir bilgiyi dışarıya sızdırmayacağını kesin olarak taahhüt eder. Ayrıca, istemli bir şekilde Vertex ekosistemine veya topluluğuna zarar verici, sabote edici herhangi bir eylemde bulunamaz.

5. Etik
Vertex, ekosistem içerisindeki iletişimin dinamik, samimi ve girişimcilik kültürünün doğasına uygun bir esneklikte olmasını destekler. Ekip içi olağan şakalaşmalar ve günlük iletişim dili doğal karşılanır. Ancak bu iletişim özgürlüğü; başka bir üyeye yönelik kasıtlı, sürekli ve ciddi boyutta rahatsızlık verici bir seviyeye (zorbalık, ağır hakaret, ayrımcılık vb.) ulaştığında etik ihlali sayılır. Bu sınırın ciddi şekilde aşılması veya Vertex’in itibarını zedeleyici hareketlerde bulunulması durumunda, durum Vertex yönetimi tarafından değerlendirilerek Katkıcı sistemden derhal uzaklaştırılabilir; Vertex’in tazminat hakları saklıdır.

6. Temsil Yetkisi ve Sınırları
Katkıcı, Vertex vizyonunu çeşitli etkinliklerde, topluluklarda ve sosyal mecralarda tanıtabilir ve ekosistemin büyümesi amacıyla yeni yeteneklerin ekibe katılmasına aracılık edebilir. Ancak bu tanıtım ve elçilik misyonu; Katkıcı’ya Vertex adına herhangi bir bağlayıcı sözleşme imzalama, hukuki veya finansal taahhüt altına girme ya da resmi bir ortaklık kurma yetkisi vermez. Katkıcı'nın temsil faaliyetleri sırasında sergilediği tutumun Vertex'in marka değerine, kurumsal itibarına veya genel vizyonuna zarar verecek nitelikte olması durumunda; Vertex yönetimi, durumu anında değerlendirerek Katkıcı'nın ekosistemle olan ilişiğini derhal kesme, tek taraflı fesih hakkını kullanma ve tazminat haklarını saklı tutar.

7. Uygulanacak Hukuk
İşbu belgeden doğabilecek her türlü uyuşmazlığın yorumlanmasında ve çözümünde İngiltere ve Galler (England & Wales) yasaları geçerli olacak ve Londra mahkemeleri yetkili kılınacaktır. Ancak Vertex, ekosisteme zarar verilmesi gibi acil durumlarda; zararı durdurmak, ihtiyati tedbir kararı aldırmak veya tazminat talep etmek amacıyla Katkıcı'nın ikamet ettiği ülkenin mahkemelerinde ve icra dairelerinde de doğrudan yasal işlem başlatma hakkını tek taraflı olarak saklı tutar.

8. Fesih
Katkıcı, etik kurallara uymakla yükümlüdür. Bulunduğu ülkenin kanunlarına göre suç teşkil eden ağır eylemlerde bulunulması veya işbu belgedeki kuralların ihlal edilmesi durumu "Kötü Ayrılık" sayılır. Kötü Ayrılık durumunda Vertex, sözleşmeyi derhal tek taraflı feshederek Katkıcı'nın ekosistemle ilişiğini kesme hakkına sahiptir. Bu şekilde ilişiği kesilen kişi, Vertex ile bağ kurma hakkını kaybeder. İhlalin Vertex'e zararı dokunması halinde, Vertex’in her türlü yasal işlem başlatma hakkı saklıdır.

9. Değişiklikler
Vertex, işbu belgede yer alan şartları, yasal gereksinimler veya ekosistemin operasyonel ihtiyaçları doğrultusunda dilediği zaman tek taraflı olarak güncelleme, değiştirme veya yeni maddeler ekleme hakkını saklı tutar. Yapılan tüm güncellemeler, Vertex ekosistemindeki iletişim kanalları üzerinden duyurulur. Duyuru yapıldığı andan itibaren, Katkıcı'nın Vertex’te faaliyet göstermeye ve işlere katkı vermeye devam etmesi, güncellenmiş şartları peşinen kabul ettiği anlamına gelir. Güncellenen şartları kabul etmeyen Katkıcı, sistemden sözleşmesini feshederek ekosistemden ayrılmakla yükümlüdür.

Onay Beyanı
Yukarıdaki şartları tamamen okuduğumu, Vertex ekosistemindeki rolümün bir istihdam ilişkisi olmadığını anladığımı, 18 yaşından küçük olmam durumunda gerekli veli veya vasi iznine sahip olduğumu, gizlilik kurallarına kati suretle uyacağımı, etik kurallara sadık kalacağımı, Vertex'in itibarını zedeleyecek hiçbir eylemde bulunmayacağımı, markayı dışarıda doğru ve sorumluluk bilinciyle temsil edeceğimi, Vertex için ürettiğim materyallerin özgün olduğunu ve haklarını Vertex’e devrettiğimi kabul ve taahhüt ederim. Sağladığım bu dijital onayın, yasal olarak bağlayıcı olduğunu beyan ederim.`;

const contractEn = `Vertex Team Contract

Introduction and Scope
This document sets forth the fundamental principles to be followed by persons supporting works performed by Vertex Corporation LTD, registered in the Companies Register of England and Wales under registration number 17133522 and hereinafter referred to as Vertex, hereinafter referred to as Contributors. In the event of any conflict of provisions between this agreement and specific agreements relating to specialized teams to which a Contributor may be involved, the provisions of the relevant specific agreement shall prevail.

1. Status
The contributor acknowledges that during their time within the Vertex ecosystem, they are not an official employee, worker, or agent of Vertex. There is no employer-employee relationship between the parties. This participation aims to gain experience in line with a shared vision, support the ecosystem, and add value to technological projects. The contributor is not guaranteed a fixed salary, wage, or insurance for these activities. However, the contributor may mention and reference this experience and role in their professional resume only for the duration of this agreement and their continued active participation in the Vertex ecosystem. Furthermore, based on their outstanding performance and commitment, the contributor has the opportunity to advance to higher levels within the ecosystem, assume strategic positions, and become a partner of Vertex, among other opportunities.

2. Representative Permission
The Contributor's legal responsibilities are governed by the laws of the country in which they reside. If the Contributor is under 18 years of age, by digitally approving this text and becoming part of the Vertex ecosystem, the Contributor declares and undertakes that they have received full authorization and permission from their parent or legal guardian to participate in Vertex-related activities, create content, represent Vertex, and transfer the intellectual property rights arising from the work they perform on behalf of Vertex as described in this document.

3. Intellectual Property
The Contributor's effort and contributions to projects within the Vertex ecosystem are undeniably acknowledged and honored. Unless the Contributor terminates their relationship with Vertex under the Bad Leaver Status described in this document, they always retain the right to freely express their contributions to these projects by referencing their names and to showcase them in their portfolio. However, in order to protect the global vision, sustainability, and integrity of the projects, all rights to the name, execution, operation, development, and commercial rights of any software, code, design, algorithm, strategy, and idea produced within or incorporated into the ecosystem belong exclusively to Vertex. The Contributor acknowledges and declares that the commercial and operational rights to their contributions are entirely vested in Vertex.

4. Confidentiality
Contributors may not share any strategic plans, unannounced projects, technical data such as code, design and architecture, or important and critical internal communications accessed while within the Vertex community with third parties, on social media, or on public platforms without Vertex's written consent. Contributors absolutely commit not to leak any confidential and critical information learned within Vertex. Furthermore, they may not intentionally engage in any action that harms or sabotages the Vertex ecosystem or community.

5. Ethics
Vertex supports dynamic, friendly, and flexible communication within the ecosystem, in line with the nature of an entrepreneurial culture. Casual banter and everyday language within the team are welcome. However, this freedom of communication is considered an ethical violation when it reaches a level of deliberate, persistent, and serious harassment towards another member (bullying, severe insults, discrimination, etc.). If this boundary is severely crossed, or if actions are taken that damage Vertex's reputation, the situation will be reviewed by Vertex management, and the contributor may be immediately removed from the system; Vertex reserves its right to compensation.

6. Representation Authority and Limitations
The contributor may promote Vertex's vision at various events, in communities, and on social media, and may facilitate the recruitment of new talent to the team to contribute to the growth of the ecosystem. However, this ambassadorial role does not authorize the contributor to sign contracts, enter into any legal or financial commitments, or establish a formal partnership on behalf of Vertex. If the contributor's conduct during their representation activities is deemed to harm Vertex's brand value, corporate reputation, or overall vision, Vertex reserves the right to immediately assess the situation and terminate the contributor's relationship with Vertex and claim compensation.

7. Applicable Law
Any disputes shall be governed by the laws of England and Wales, with London courts having jurisdiction. However, to prevent damage to the ecosystem, Vertex reserves the right to seek immediate injunctive relief or compensation in the courts of the Contributor's country of residence.

8. Termination
The contributor is obligated to comply with ethical guidelines. Engaging in serious acts that constitute a crime under the laws of the country of residence, or violating the rules in this document, will be considered a "Bad Leaver Status". In the event of a Bad Leaver Status, Vertex reserves the right to immediately terminate the contract unilaterally, severing the contributor's connection with the ecosystem. The individual thus severed loses the right to establish a relationship with Vertex. Vertex reserves the right to initiate all necessary legal proceedings if the violation causes harm to Vertex.

9. Amendments
Vertex reserves the right to unilaterally update, modify, or add new clauses to the terms contained in this document at any time, in accordance with legal requirements or the operational needs of the ecosystem. All updates will be announced through the communication channels within the Vertex ecosystem. From the moment of announcement, the Contributor's continued participation in Vertex activities and contributions to its operations constitutes acceptance of the updated terms. Contributors who do not accept the updated terms are obligated to terminate their contract and leave the ecosystem.

Consent Statement
I acknowledge and agree that I have fully read the above terms and conditions, understand that my role within the Vertex ecosystem is not an employment relationship, have the necessary parental or guardian consent if I am under 18 years of age, will strictly adhere to privacy rules, will remain committed to ethical guidelines, will not engage in any actions that would damage Vertex's reputation, will represent the brand accurately and responsibly externally, and that the materials I produce for Vertex are original and that I transfer all rights to them to Vertex. I declare that this digital consent is legally binding.`;

module.exports = { contractTr, contractEn };
